# Homework 1 - Numpy

For all the questions, print the results with a variable of your choice (e.g., Z)

#### 1. Import the numpy package under the name `np` 

In [1]:
import numpy as np

#### 2. Create a vector with values ranging from 10 to 49 

In [3]:
v2 = (np.arange(10,50))
print(v2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 3. Reverse a vector (first element becomes last) 

In [4]:
v2_r = v2[::-1]
print(v2_r)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 4. Create a 3x3 matrix with values ranging from 0 to 8 

In [5]:
v4 = np.arange(0,9).reshape(3,3)
print(v4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 5. Find indices of non-zero elements from [1,2,0,0,4,0] 

In [6]:
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)


#### 6. Create a 3x3 identity matrix 

In [7]:
m6 = np.eye(3)
print(m6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 7. Create a 3x3x3 array with random values 

In [8]:
v7 = np.random.rand(3,3,3)
print(v7)

[[[0.14615307 0.06456692 0.72553962]
  [0.67158007 0.95976864 0.64631333]
  [0.93501885 0.68469624 0.14417364]]

 [[0.36270309 0.65920183 0.85508002]
  [0.18215199 0.00833646 0.43604768]
  [0.25780075 0.28215192 0.39364496]]

 [[0.17043029 0.57431033 0.68267043]
  [0.94407909 0.11464601 0.40539698]
  [0.3124196  0.6069794  0.57055172]]]


#### 8. Create a 10x10 array with random values and find the minimum and maximum values 

In [28]:
v8 = np.random.rand(10,10)
n = len(v8)
print(v8)

def maxi(v, n, m):
    
    
def mini(v, n):
    if n ==1:
        return v8[0]
    max_n_1 = mini(v8, n-1)
    if max_n_1 > v8[n-1]:
        return max_n_1
    else:
        return v8[n-1]

SyntaxError: invalid syntax (<ipython-input-28-2968432b508e>, line 6)

#### 9. Create a checkerboard 8x8 matrix using np.array([0,1],[1,0]) and the tile function  

In [21]:
v_9 = np.array(([0,1], [1,0]))
v9 = np.tile(v_9,(4,4))
print(v9)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 10. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [22]:
v10_a = np.arange(15).reshape(5,3)
v10_b = np.arange(6).reshape(3,2)

print(v10_a, v10_b)

innerproduct10 = v10_a.dot(v10_b)
print(innerproduct10)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]] [[0 1]
 [2 3]
 [4 5]]
[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


#### 11. Create a 5x5 matrix with row values ranging from 0 to 4 using tile function as follows:


In [68]:
m_11 = np.arange(5)
m11 = np.tile(m_11,(5,1))
print(m11)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 12. Create a 5x5 matrix with row values ranging from 0 to 4 using broadcasting


In [ ]:
v12 = [] 
v_12 = np.arange(25).reshape(5,5)
print(v12, v_12)
for k in range(0,25) :
    
    

#### 13. Create a random vector of size 10 and sort it 

In [67]:
####built-in version

v13 = np.random.randn(10)
print(sorted(v13))



####without built-in function

v13 = np.random.randn(10)
new_list = []

while any(v13):
    minimum = v13[0] 
    for x in v13: 
        if x < minimum:
            minimum = x
    new_list.append(minimum)
    v13 = np.delete(v13, np.where(v13==minimum)) 

print(new_list)

[-2.482091296716108, -1.3192865663994, -0.3739989609346384, -0.13602608232486166, -0.06474222480721392, 0.34931485014475205, 0.3682715631151103, 0.803551577769007, 1.2160173650880666, 1.6364037394562387]
[-1.556656583759207, -1.0681373478917244, -0.28271148077993996, -0.19535237537078579, 0.004124406073502934, 0.07082215248277726, 0.1845979816199203, 0.7864168241576236, 0.7959885196093576, 1.222441188280355]


#### 14. Subtract the mean of each row

X = np.random.rand(5,10)

In [26]:
X = np.random.rand(5,10)
print(X)
v14 = np.mean(X, axis=1)
print(v14)

[[0.94298333 0.92681726 0.02834386 0.13556644 0.14426386 0.9518215
  0.34910829 0.34314727 0.08656843 0.74960996]
 [0.08438204 0.80448398 0.09377835 0.09665793 0.25781691 0.6499493
  0.23053885 0.29829761 0.91701176 0.67133639]
 [0.72138552 0.28245268 0.14832644 0.51956483 0.76172625 0.01380845
  0.88260349 0.69331663 0.85574665 0.30200535]
 [0.22524371 0.51370183 0.03129776 0.86991335 0.80759427 0.06939645
  0.08140217 0.47061937 0.31767234 0.26435399]
 [0.92433165 0.68621326 0.79085643 0.98897695 0.59026636 0.71012813
  0.69401448 0.23228655 0.7851159  0.28398598]]
[0.46582302 0.41042531 0.51809363 0.36511952 0.66861757]


#### 15. Create, 10 by 10 multiplication table from 1 to 10

In [82]:
### for loop
t_15 = [i*j for i in range(1,11) for j in range(1,11)]
t15 = np.reshape(t_15,(10,10))
print(t15)

### broadcasting
np.arange(1, 11)*np.arange(1, 11).reshape(10, 1)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

#### 16. How to get the diagonal of a dot product? 

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

In [41]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A, B)

v16 = np.diag(np.diag(A.dot(B)))
print(v16)

[[0.74707288 0.45815986 0.8745611  0.57269657 0.83555392]
 [0.49374675 0.03096268 0.60528482 0.50003261 0.78627128]
 [0.8838792  0.89664136 0.86336024 0.61243795 0.40418737]
 [0.88040718 0.43748845 0.54918751 0.10668524 0.14000917]
 [0.72787568 0.42523342 0.91767084 0.81426141 0.16646906]] [[0.62428109 0.8577788  0.38956918 0.84029028 0.86847917]
 [0.79780105 0.62645848 0.67764367 0.99577738 0.36018271]
 [0.2562614  0.49368809 0.33583718 0.94434907 0.8329944 ]
 [0.19265897 0.84871941 0.72142992 0.43222741 0.4958473 ]
 [0.1808704  0.33433853 0.87597654 0.66201488 0.21898035]]
[[1.31748224 0.         0.         0.         0.        ]
 [0.         1.4290124  0.         0.         0.        ]
 [0.         0.         2.03777361 0.         0.        ]
 [0.         0.         0.         1.83286386 0.        ]
 [0.         0.         0.         0.         1.98992404]]


#### 17. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

In [18]:
##version 1
#####################
import numpy as np

v_17 = np.array([1,2,3,4,5])

for k in range(4) :
    idx_ = np.nonzero(v_17)
    idx_v = idx_[0]
    idx = idx_v[k]
    a = v_17[:idx+1]
    b = v_17[idx+1:]
    a = np.append(a, [0,0,0])
    v_17 = np.append(a, b)
    
print(v_17)

##version 2
######################

list1 = [1, 2, 3, 4, 5]
list2 = []
for i in range(len(list1)):
    list2.append(list1[i])
    if i < 4:
        for i in range(3):
            list2.append(0)
print(list2)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]
[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


#### 18. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

#### 19. How to swap two rows of an array? Generate an array from 0 to 24, and reshape it 5 by 5 and swap first two rows of the array

In [76]:
v_19 = np.arange(25).reshape(5,5)
print(v_19)

v_19[[0, 1]] = v_19[[1, 0]]
print(v_19)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 20. How to find the most frequent value in an array? 

Z = np.random.randint(0,10,50). hint: np.bincount, np.argmax

In [81]:
Z = np.random.randint(0,10,50)
print(Z)
counts = np.bincount(Z)
print(counts)
print(np.argmax(counts))

[3 5 1 8 1 0 4 5 4 9 5 8 5 0 4 1 4 7 5 0 0 7 0 7 0 3 4 2 1 6 7 9 2 9 1 3 9
 6 3 4 9 9 0 5 3 2 2 5 6 6]
[7 5 4 5 6 7 4 4 2 6]
0


#### 21. How to get the n largest values of an array?

start with 
Z = np.arange(10000);
np.random.shuffle(Z)
, Hint: np.argsort

In [31]:
import numpy as np

n = int(input())
Z = np.arange(10000)
np.random.shuffle(Z)
print(Z)

idx21 = np.argsort(Z)[::-1]
print(idx21)
a21 = [Z[idx21[k]] for k in range(n)]

print('The n largest values are : {}' .format(a21))

3
[ 463 5121 2319 ... 7032 4852 9854]
[6289 1633 9210 ... 9173 6459 4528]
The n largest values are : [9999, 9998, 9997]


#### 22. Given a two dimensional array, how to extract unique rows? 

Hint: np.unique

#### 23. How to compute averages using a sliding window over an array? 

make a function with two arguments, arry and size of the sliding window, def moving_avg(arr, n)


In [ ]:
def moving_avg(arr, n):
    
    

#### 24. Find the indices of elements from 4 by 4 random matrix (0-1) which are larger than 0.5

Print a list of tuples indicating the index for row and column


In [88]:
v_24 = np.random.rand(16).reshape(4,4)
idx = (v_24>0.5).nonzero()

v24 = [*zip(idx[0],idx[1])]
print(v24)

[(0, 1), (0, 2), (1, 1), (1, 2), (2, 1), (2, 2), (2, 3), (3, 1)]


#### 25. Write a function returning distance between two points

In [17]:
import math

a = input()
b = input()

def distnce(m, n):
    
    y = math.sqrt((int(a[0])-int(b[0]))**2 + (a[1]-b[1])**2)
    return y  
    
    
distnce(a, b)
    

KeyboardInterrupt: Interrupted by user